services:
  - type: web
    name: emotion-music-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        generateValue: true
      - key: PYTHONUNBUFFERED
        value: 1
      - key: TF_CPP_MIN_LOG_LEVEL
        value: 2
      - key: DEEPFACE_HOME
        value: /tmp/.deepface