services:
  - type: web
    name: emotion-music-app
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install --no-cache-dir -r requirements.txt || pip install --no-cache-dir -r requirements-light.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 300 --workers 1 --max-requests 100 --preload
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        generateValue: true
      - key: PYTHONUNBUFFERED
        value: 1
      - key: TF_CPP_MIN_LOG_LEVEL
        value: 2
      - key: OPENCV_VIDEOIO_PRIORITY_MSMF
        value: 0
      - key: DEEPFACE_HOME
        value: /tmp/.deepface